### ISSUE TITLE
How to train the model with my own child image dataset?

### ISSUE THREAD

**Issue by chen990627** [yxuhan/ReflectanceMM#2]

**Comment by chen990627** [comment]
> _No description provided._

sorry to bother you.

**Comment by yxuhan** [comment]
Hi @chen990627, currently we only support train on the provided FFHQ dataset. 

To train our model on your dataset, I suggest you first run our code successfully, and then prepare the same data format as the preprocessed FFHQ dataset we provided.

**Comment by chen990627** [comment]
> Hi @chen990627, currently we only support train on the provided FFHQ dataset.
> 
> To train our model on your dataset, I suggest you first run our code successfully, and then prepare the same data format as the preprocessed FFHQ dataset we provided.

OK, thanks for suggestion!
