### ISSUE TITLE
How to get other format output?

### ISSUE THREAD

**Issue by Talegqz** [yxuhan/ReflectanceMM#3]
Thank you for your outstanding work. 
I wanted to express my gratitude for successfully running the code. 
However, I noticed that the output only consists of images. 
Could you please assist me in obtaining output in other formats?
Thank you once again for your assistance.

**Comment by yxuhan** [comment]
Hi, thanks for your interest in our work. What do you mean by other formats? For UV formats, you can use the `generateTextureFromAlbedo` function in `models\facemodel\basemm.py` to convert vertex attributes to UV maps.  The estimated vertex attributes can be found in `render` function in `models\refmm_model.py`, e.g. `self.pred_diff`.

**Comment by Talegqz** [comment]
Thanks for your help！
